### ISSUE TITLE
[Feature Request] [Obsidian] Incorporate note name (file name) in search

### ISSUE THREAD

**Issue by eduongAZ** [debanjum/khoj#142] opened 2023-02-06 23:25 UTC
It seems that khoj does not consider the file name in its search.

I named a file to describe a piece of code in the file content. When I search for the file with khoj using words only present in the file name, it does not report that file.

It would be great if khoj also considers the file name as well during search.

**Comment by sohanglal** [comment] 2023-02-07 04:08
Duplicate of #134

**Comment by debanjum** [comment] 2023-02-07 04:19
> Duplicate of #134

I initially thought that too (based on the issue title) but this is a request to index the filename for search. 
Whereas #134 is about displaying the filename of the entry in the results. These are not the same thing.

**Comment by sohanglal** [comment] 2023-02-07 04:21
My bad

**Closed** 2023-03-30 07:15 UTC
